---
language: php

sudo: required

php:
  - 8.0

services:
  - mysql

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
